"""Deterministic, read-only code projection contracts and services."""

from vault_graph.code_index.code_generation import (
    CodeGenerationError,
    CodeGenerationLayout,
    CodeProjectionGenerationManager,
)
from vault_graph.code_index.code_models import (
    CODE_DART_GRAMMAR_REVISION,
    CODE_DART_GRAMMAR_SOURCE,
    CODE_DART_GRAMMAR_SOURCE_REVISION,
    CODE_EXTRACTION_STATUSES,
    CODE_FRESHNESS_STATES,
    CODE_PARSER_SPEC_VERSION,
    CODE_PROJECTION_SCHEMA_VERSION,
    CODE_RELATION_KINDS,
    CODE_SYMBOL_KINDS,
    CodeApplyResult,
    CodeEdgeRecord,
    CodeExtractionStatus,
    CodeFileInput,
    CodeFileOutlineRequest,
    CodeFileOutlineResponse,
    CodeFileSnapshot,
    CodeFreshnessReport,
    CodeFreshnessRequest,
    CodeFreshnessState,
    CodeImpactRequest,
    CodeIndexCliRequest,
    CodeIndexCliResponse,
    CodeIndexMode,
    CodeIndexPlan,
    CodeIndexRequest,
    CodeManifest,
    CodeOutputFormat,
    CodeParseDiagnostic,
    CodeParseResult,
    CodeReconcilePlan,
    CodeReferenceRecord,
    CodeRelationKind,
    CodeRepositoryAddRequest,
    CodeRepositoryEntry,
    CodeRepositoryId,
    CodeRepositoryListRequest,
    CodeRepositoryListResponse,
    CodeRepositoryMutationResponse,
    CodeRepositoryRemoveRequest,
    CodeRunReport,
    CodeSearchResponse,
    CodeStatusRequest,
    CodeStatusResponse,
    CodeSymbolHit,
    CodeSymbolKind,
    CodeSymbolQuery,
    CodeSymbolRecord,
    CodeSymbolRequest,
    CodeSymbolResponse,
    CodeSymbolSearchRequest,
    CodeTraversalDirection,
    CodeTraversalQuery,
    CodeTraversalRequest,
    CodeTraversalResponse,
    CodeTraversalResult,
    PendingCodeReference,
    ResolutionResult,
    code_file_identity,
)
from vault_graph.code_index.dart_parser import DartCodeParserAdapter, DartParserAdapter
from vault_graph.code_index.parser_adapter import CodeParserAdapter
from vault_graph.code_index.python_parser import PythonCodeParserAdapter, PythonParserAdapter
from vault_graph.code_index.reference_resolution import CodeReferenceResolver
from vault_graph.code_index.repository_catalog import (
    SUPPORTED_CODE_LANGUAGES,
    SUPPORTED_GIT_REVISION_POLICIES,
    CodeRepositoryCatalog,
    CodeRepositoryCatalogService,
    repository_policy_revision,
)
from vault_graph.code_index.source_scanning import (
    CodeScanResult,
    CodeSourceScanError,
    CodeSourceScanner,
    ScanResult,
    SourceScanner,
    scan_repository,
)


def __getattr__(name: str) -> object:
    """Load orchestration services lazily to keep storage imports acyclic."""

    if name in {"CodeFreshness", "CodeFreshnessService"}:
        from vault_graph.code_index.code_freshness import CodeFreshness, CodeFreshnessService

        return {"CodeFreshness": CodeFreshness, "CodeFreshnessService": CodeFreshnessService}[name]
    if name == "CodeProjectionService":
        from vault_graph.code_index.code_projection_service import CodeProjectionService

        return CodeProjectionService
    if name == "CodeQueryService":
        from vault_graph.code_index.code_query_service import CodeQueryService

        return CodeQueryService
    raise AttributeError(name)


__all__ = [
    "CODE_DART_GRAMMAR_REVISION",
    "CODE_DART_GRAMMAR_SOURCE",
    "CODE_DART_GRAMMAR_SOURCE_REVISION",
    "CODE_PARSER_SPEC_VERSION",
    "CODE_PROJECTION_SCHEMA_VERSION",
    "CODE_EXTRACTION_STATUSES",
    "CODE_FRESHNESS_STATES",
    "CODE_RELATION_KINDS",
    "CODE_SYMBOL_KINDS",
    "CodeApplyResult",
    "CodeEdgeRecord",
    "CodeFileInput",
    "CodeFileSnapshot",
    "CodeFreshnessReport",
    "CodeFreshnessRequest",
    "CodeIndexPlan",
    "CodeIndexRequest",
    "CodeManifest",
    "CodeParseDiagnostic",
    "CodeParseResult",
    "CodeReferenceRecord",
    "CodeReconcilePlan",
    "CodeRepositoryEntry",
    "CodeRunReport",
    "CodeSymbolHit",
    "CodeSymbolQuery",
    "CodeSymbolRecord",
    "CodeTraversalQuery",
    "CodeTraversalResult",
    "PendingCodeReference",
    "ResolutionResult",
    "CodeReferenceResolver",
    "code_file_identity",
    "CodeRepositoryId",
    "CodeExtractionStatus",
    "CodeFreshnessState",
    "CodeIndexMode",
    "CodeOutputFormat",
    "CodeRelationKind",
    "CodeSymbolKind",
    "CodeTraversalDirection",
    "CodeGenerationError",
    "CodeGenerationLayout",
    "CodeProjectionGenerationManager",
    "CodeFreshness",
    "CodeFreshnessService",
    "CodeProjectionService",
    "CodeQueryService",
    "CodeScanResult",
    "CodeSourceScanError",
    "CodeSourceScanner",
    "ScanResult",
    "SourceScanner",
    "scan_repository",
    "CodeRepositoryCatalog",
    "CodeRepositoryCatalogService",
    "SUPPORTED_CODE_LANGUAGES",
    "SUPPORTED_GIT_REVISION_POLICIES",
    "repository_policy_revision",
    "CodeParserAdapter",
    "PythonCodeParserAdapter",
    "PythonParserAdapter",
    "DartCodeParserAdapter",
    "DartParserAdapter",
    "CodeRepositoryAddRequest",
    "CodeRepositoryListRequest",
    "CodeRepositoryRemoveRequest",
    "CodeRepositoryListResponse",
    "CodeRepositoryMutationResponse",
    "CodeIndexCliRequest",
    "CodeIndexCliResponse",
    "CodeStatusRequest",
    "CodeStatusResponse",
    "CodeSymbolSearchRequest",
    "CodeSymbolRequest",
    "CodeFileOutlineRequest",
    "CodeTraversalRequest",
    "CodeImpactRequest",
    "CodeSearchResponse",
    "CodeSymbolResponse",
    "CodeFileOutlineResponse",
    "CodeTraversalResponse",
]
